alert("Bem-vindo ! A seguir pediremos que informe alguns dados.")
let name = prompt("Qual seu nome ?")
let age = prompt("Qual sua idade ?")
let confirmation = confirm("Sua idade é " + age + " anos ?")
alert("Nome: "+ name + "\nIdade: " + age + "\nConfirmação: " + confirmation)