console.info("Bem Vindo á Nave")
console.log("Bem Vindo á Nave")
console.warn("Bem Vindo á Nave")
console.error("Bem Vindo á Nave")
alert("BEM VINDO")
prompt("ESTÁ TUDO PRONTO ?")
confirm("Esá ai piloto ?")